### ISSUE TITLE
Issue on the sudo step

### ISSUE THREAD

**Issue by ml334422** [No3x/MMM-GoogleDocs-Notes#33]
I am getting this error when I get to this step sudo... am I missing the google auth module?

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'google-auth-library'
Require stack:
- /home/ml/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ml/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/ml/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.js' ]

**Comment by ml334422** [comment]
Okay I tried installing the googleapis in the main directory for my username and now I get this error

TypeError: Cannot read property '0' of undefined

**Comment by No3x** [comment]
Duplicate. See #24
