### ISSUE TITLE
error when executing authorize.mjs

### ISSUE THREAD

**Issue by EddieBrito** [No3x/MMM-GoogleDocs-Notes#60]
I have ran "node authorize.mjs" in my terminal and I get the following error.

node authorize.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'axios' imported from /home/pi/MagicMirror/modules/MMM-GoogleDocs-Notes/authorize.mjs
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by No3x** [comment]
Hi, you are probably missing a `npm install`.
